apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
      ports:
      - containerPort: 80