apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sshalunos2-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sshalunos2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sshalunos2
  template:
    metadata:
      labels:
        app: sshalunos2
    spec:
      containers:
      - name: sshalunos2
        image: erickweil/container-ssh:latest
        resources: {}
        envFrom:
        - configMapRef:
            name: sshalunos-cm
        ports:
        - containerPort: 22
        volumeMounts:
        - name: vol
          mountPath: /home
          subPath: home

      # Pod docker junto com o pod do acesso ssh, assim as portas exposta são disponíveis
      # via localhost
      # https://hub.docker.com/r/jpetazzo/dind
      # http://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/
      # https://hub.docker.com/_/docker/
      - name: docker
        image: docker:dind 
        command: ["dockerd", "--host", "tcp://0.0.0.0:2375"]
        #args: ["--exec-opt", "native.cgroupdriver=systemd"]
        resources: {}
        securityContext: 
            privileged: true 
        volumeMounts:
        # Para funcionar bind mounts
        - name: vol
          mountPath: /home
          subPath: home 
        # Para poder restart=unless-stopped e também ficar o cache das imagens
        - name: vol
          mountPath: /var/lib/docker 
          subPath: docker
        - name: vol-daemon
          mountPath: /etc/docker
      volumes: 
      - name: vol
        persistentVolumeClaim:
          claimName: sshalunos2-pvc
      - name: vol-daemon
        configMap:
          name: sshalunos-docker-cm
          items:
            - key: daemon
              path: daemon.json
      # https://stackoverflow.com/questions/60247100/hostpath-assign-persistentvolume-to-the-specific-work-node-in-cluster
      affinity:               
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-erick-controller-1
---
apiVersion: v1
kind: Service
metadata:
  name: sshalunos2
spec:
  type: NodePort
  selector:
    app: sshalunos2
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    nodePort: 31023
---
apiVersion: v1
kind: Service
metadata:
  name: docker2
spec:
  type: ClusterIP
  selector:
    app: sshalunos2
  ports:
  - name: sock
    port: 2375
    targetPort: 2375
  - name: http
    port: 80 
    targetPort: 80