apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilplace-site-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilplace-site-deploy
  template:
    metadata:
      labels:
        app: weilplace-site-deploy
    spec:
      containers:
      - name: weilplace-site-deploy
        image: erickweil/weilplace-site:latest
        env:
        - name: APISERVER
          valueFrom:
            configMapKeyRef:
              name: weilplace-cm
              key: APISERVER
        resources: {}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: weilplace-site-svc
spec:
  type: NodePort
  selector:
    app: weilplace-site-deploy
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31100