apiVersion: v1
kind: PersistentVolume
metadata:
  name: weilplace-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/volume/weilplace"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weilplace-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual
  volumeName: weilplace-pv
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilplace-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilplace-api-deploy
  template:
    metadata:
      labels:
        app: weilplace-api-deploy
    spec:
      containers:
      - name: weilplace-api-deploy
        image: erickweil/weilplace-api:latest
        envFrom:
          - configMapRef:
              name: weilplace-cm
        args: ["-placedelay","$(PLACEDELAY)","-size","$(SIZE)"]
        resources: {}
        ports:
        - containerPort: 8090
        volumeMounts:
          - mountPath: /opt/app/img
            name: pv
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: weilplace-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: weilplace-api-svc
spec:
  type: NodePort
  selector:
    app: weilplace-api-deploy
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 31101