apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weilplace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weilplace-api-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weilplace-api-deploy
  template:
    metadata:
      labels:
        app: weilplace-api-deploy
    spec:
      containers:
      - name: weilplace-api-deploy
        image: erickweil/weilplace-api:latest
        envFrom:
          - configMapRef:
              name: weilplace-cm
        args: ["-placedelay","$(PLACEDELAY)","-size","$(SIZE)"]
        resources: {}
        ports:
        - containerPort: 8090
        volumeMounts:
          - mountPath: /opt/app/img
            name: pv
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: weilplace-pvc
      # Definindo affinidade para usar o mesmos dados
      # Quando o volume é 'local-path' cada node vai
      # ter o seu. Se não especificar pode iniciar o volume vazio em outro node.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - k3s-erick-worker
---
apiVersion: v1
kind: Service
metadata:
  name: weilplace-api-svc
spec:
  type: NodePort
  selector:
    app: weilplace-api-deploy
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 30090