apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erick-mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erick-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erick-mongo
  template:
    metadata:
      labels:
        app: erick-mongo
    spec:
      containers:
      - name: mongo-db
        image: mongo:latest
        resources: {}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: pv
          mountPath: /data/db
      volumes:
      - name: pv
        persistentVolumeClaim:
          claimName: erick-mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: erick-mongodb
spec:
  selector:
    app: erick-mongodb
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017