apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erick-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: erick-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erick-mongo
  template:
    metadata:
      labels:
        app: erick-mongo
    spec:
      containers:
      - name: "mongo-db"
        image: "mongo:4.4.6"
        resources: {}
        imagePullPolicy: "Always"
        env:
        - name: "MONGO_INITDB_ROOT_USERNAME"
          value: "erick"
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          value: "12345678"
        ports:
        - containerPort: 27017
          name: "mongodb"
        volumeMounts:
        - name: "mongodb-persistent-storage"
          mountPath: "/data/db"
    volumes:
    - name: "mongodb-persistent-storage"
      persistentVolumeClaim:
      claimName: "erick-mongo-pvc"
---
apiVersion: v1
kind: Service
metadata:
  name: erick-mongo
spec:
  selector:
    app: erick-mongo
  type: NodePort
  ports:
  - port: 27017
    targetPort: 27017
    nodePort: 30017