apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-banco
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodejs-banco
  template:
    metadata:
      labels:
        app: nodejs-banco
    spec:
      containers:
      - name: nodejs-banco
        image: erickweil/nodejs-k8s-banco:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: TITULO
          value: "NODEJS COM BANCO NO KUBERNETES"
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_PORT
          value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-banco
spec:
  type: NodePort
  selector:
    app: nodejs-banco
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1 # BANCO DE DADOS 1 REPLICA SÓ
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        resources:
          limits:
            memory: "2Gi"
            cpu: "2.0"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017