apiVersion: apps/v1
kind: Deployment
metadata:
  name: erick-logs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erick-logs
  template:
    metadata:
      labels:
        app: erick-logs
    spec:
      containers:
      - name: erick-logs
        image: erickweil/nodejs-k8s-banco:2.0.0
        resources: {}
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: TITULO
          value: "NODEJS COM BANCO NO KUBERNETES"
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: erick-mongodb-config
              key: DB_URL
        # Configure aqui o url de conexão com o banco
        #  value: "mongodb://mongodb:27017/nodeaula"
---
apiVersion: v1
kind: Service
metadata:
  name: erick-logs
spec:
  type: ClusterIP
  selector:
    app: erick-logs
  ports:
  - port: 80
    targetPort: 3000