# A ideia é poder executar comandos docker dentro de um Pod
# Apenas para testar
# https://applatix.com/case-docker-docker-kubernetes-part-2/
---
apiVersion: v1 
kind: Pod 
metadata: 
    name: erick-dockerteste 
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:latest
        #command: ['docker', 'run', '-p', '80:80', 'httpd:latest'] 
        command: ['/bin/sh','-c','while sleep 3600; do :; done'] 
        resources: {}
        env: 
          - name: DOCKER_HOST 
            value: tcp://localhost:2375 
      - name: dind-daemon 
        image: docker:dind 
        command: ["dockerd", "--host", "tcp://127.0.0.1:2375"]
        #args: ["--exec-opt", "native.cgroupdriver=systemd"]
        resources: {}
        securityContext: 
            privileged: true 
        volumeMounts: 
          - name: docker-graph-storage 
            mountPath: /var/lib/docker 
    volumes: 
      - name: docker-graph-storage 
        emptyDir: {}